package frame.zzt.com.appframe.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import frame.zzt.com.appframe.greendao.User;
import frame.zzt.com.appframe.greendao.Location;

import frame.zzt.com.appframe.greendao.UserDao;
import frame.zzt.com.appframe.greendao.LocationDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig locationDaoConfig;

    private final UserDao userDao;
    private final LocationDao locationDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        locationDaoConfig = daoConfigMap.get(LocationDao.class).clone();
        locationDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        locationDao = new LocationDao(locationDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Location.class, locationDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        locationDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public LocationDao getLocationDao() {
        return locationDao;
    }

}
